-- Schema inicial do agendamento-service.
-- DDL propositalmente neutra (SQL padrao) para rodar tanto em PostgreSQL (producao)
-- quanto em H2 (testes de integracao), garantindo que as migracoes sejam testadas.

CREATE TABLE usuario (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome  VARCHAR(120) NOT NULL,
    email VARCHAR(180) NOT NULL UNIQUE,
    senha VARCHAR(100) NOT NULL,
    role  VARCHAR(20)  NOT NULL
);

CREATE TABLE paciente (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id      BIGINT      NOT NULL UNIQUE,
    cpf             VARCHAR(14) NOT NULL UNIQUE,
    telefone        VARCHAR(20),
    data_nascimento DATE,
    CONSTRAINT fk_paciente_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id)
);

CREATE TABLE medico (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id    BIGINT      NOT NULL UNIQUE,
    crm           VARCHAR(20) NOT NULL UNIQUE,
    especialidade VARCHAR(80) NOT NULL,
    CONSTRAINT fk_medico_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id)
);

CREATE TABLE consulta (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id   BIGINT        NOT NULL,
    medico_id     BIGINT        NOT NULL,
    data_hora     TIMESTAMP     NOT NULL,
    status        VARCHAR(20)   NOT NULL,
    observacoes   VARCHAR(1000),
    criado_em     TIMESTAMP     NOT NULL,
    atualizado_em TIMESTAMP     NOT NULL,
    CONSTRAINT fk_consulta_paciente FOREIGN KEY (paciente_id) REFERENCES paciente (id),
    CONSTRAINT fk_consulta_medico FOREIGN KEY (medico_id) REFERENCES medico (id)
);

-- Consultas sao sempre lidas por paciente (historico e agenda futura).
CREATE INDEX idx_consulta_paciente_data ON consulta (paciente_id, data_hora);
