-- Schema do notificacao-service. DDL neutra (roda em PostgreSQL e em H2 nos testes).

-- Projecao local das consultas, alimentada pelos eventos do agendamento-service.
-- O id NAO e gerado aqui: e o mesmo id da consulta na origem, o que torna o
-- consumo idempotente (reprocessar um evento apenas sobrescreve a linha).
CREATE TABLE consulta_agendada (
    id             BIGINT       PRIMARY KEY,
    paciente_nome  VARCHAR(120) NOT NULL,
    paciente_email VARCHAR(180) NOT NULL,
    medico_nome    VARCHAR(120) NOT NULL,
    data_hora      TIMESTAMP    NOT NULL,
    status         VARCHAR(20)  NOT NULL,
    atualizado_em  TIMESTAMP    NOT NULL
);

-- O agendador varre exatamente por (status, data_hora).
CREATE INDEX idx_consulta_agendada_status_data ON consulta_agendada (status, data_hora);

-- Registro auditavel dos envios.
CREATE TABLE notificacao (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consulta_id        BIGINT        NOT NULL,
    tipo               VARCHAR(20)   NOT NULL,
    destinatario       VARCHAR(180)  NOT NULL,
    assunto            VARCHAR(200)  NOT NULL,
    mensagem           VARCHAR(2000) NOT NULL,
    data_hora_consulta TIMESTAMP     NOT NULL,
    status             VARCHAR(20)   NOT NULL,
    enviado_em         TIMESTAMP     NOT NULL,
    erro               VARCHAR(500)
);

-- Suporta a checagem de idempotencia do lembrete diario.
CREATE INDEX idx_notificacao_idempotencia
    ON notificacao (consulta_id, tipo, data_hora_consulta, status);
